### ISSUE TITLE
v0.12 `group-heading-level` 

### ISSUE THREAD

**Issue by quachpas** [typst-community/glossarium#67]
Hi, two questions about the `group-heading-level` fix:

1- Sorry for bothering, but what's the current status on this?

2- Wouldn't it be better if the default value for group heading levels, instead of being "the same as the previous", was "the same as the previous, plus one"? I understand that this PR aims to allow the user to choose, but the thing is that the default value before Typst 0.12 was "plus one", and honestly it seems more logical to me (I'm open to counter-arguments though). Besides, I've only just noticed, completely by chance, that the current value breaks my post-0.12 template, and I suspect that this breakage is the same with the majority of the users at this point.

_Originally posted by @tfachada in https://github.com/typst-community/glossarium/issues/60#issuecomment-2425188117_

**Comment by tfachada** [comment]
For the sake of the argument, might as well post my followup to a reply that comment got:

> My point with +1 being more logical is that a group is supposed to be a subcategory of terms within the glossary, and as such having a h1 "Glossary" title followed by also h1 titles for groups would be the same thing logically (in terms of outline) as multiple glossaries. Though then again, the workaround I found, which I suppose may be the same as yours, would be to print multiple glossaries too but with h2 titles before the subcategory ones, so the group feature might be pointless.

Personally, I am at this point indifferent to what is done here, since I went with said workaround (implemented [here](https://github.com/tfachada/thesist/blob/v0.2.0/template/Beginning/Glossary.typ)). I still think right now, though, that if the `group` feature is to be kept, then it should be in the +1 form.
