### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by internettechnik** [typst-community/glossarium#80]
unfortunately, the alignment seems to be centered now (0.5.1) which differs from 0.5.0 and cannot be changed / set with set text align directive.

**Comment by quachpas** [comment]
I wouldn't be able to guess what changed. Could you isolate your code for an example? It works on 0.5.0?

**Comment by quachpas** [comment]
@internettechnik ?

**Comment by RBW1999** [comment]
### Issue
I myb had the same "issue". I didn't check between version, but I also had same wired styling when importing the package.

My issue was user related. The styles that I had applied before were the cause of the bad alignment.

![image](https://github.com/user-attachments/assets/36bb7eaa-1644-4005-92eb-98760f2a8ea4)

### The "Cause"

I guess glossarium uses figures and captions under the hood to link and display the entries in the glossar. So your individual styling of figures and captions will take effect on the glossar. As I understand it, this functionality of leaving the styling to the user is intendet ( #60 )

Sadly I wasnt able to reproduce a isolated example in my given time. But I can present and explain my fix.

### Solution for my Issue
![image](https://github.com/user-attachments/assets/a064a07e-1a11-4603-b3da-cf21a5fa209e)

```typst
[
    #set figure(placement: none)
    #show figure: set block(width: 100%)
    #show figure.caption: c =>[
      #align(left, [#c.body])
    ]
  
    #heading([Glossar]) 
    glossarium.print-glossary(glossar-list)
 ]
 ```

1. I wrapped the styling and the glossar with a content block `[ ]` so that the style adjustment only affects the glossar.
2. Setting the figure placement to none keeps the entries from floating to the top or bottom of the page (`#set figure(placement: none)`) 
3. As discussed in this[ typst-issue-1498](https://github.com/typst/typst/issues/1498) the caption placement depents on the size of the figure. I therefore set the width `#show figure: set block(width: 100%)`
4. After setting the width to 100% the align comment works as intendet:
```typst
#show figure.caption: c =>[
      #align(left, [#c.body])
    ]
```

**Comment by quachpas** [comment]
If you are styling `figure.caption` of all kinds, it will affect glossary entries, as they are indeed figure elements.
Glad you got it working!

**Comment by internettechnik** [comment]
Dear RBW1999: Thanks for your explanations and the workaround / fix

For me following workaround works so far:

// FIX left alignment of glossary:
//      With glossary 0.5.1 it is necessary
//      to overwrite figure captions to be aligned left
#show figure.caption: c => block(width:100%,align(left, [#c.body]))
#print-glossary(gls-entries)

@quachpas ... You could try this workaround solution for the "bug" by upgrading glossarium from 0.5.0 to 0.5.1 at the example given at: https://git-iit.fh-joanneum.at/oss/thesis-template

**Comment by internettechnik** [comment]
<img width="1026" alt="glossary-version-050" src="https://github.com/user-attachments/assets/bd0bd35d-c8c9-4450-b40e-99fb01eecc4c">
<img width="646" alt="glossary-aligned-left-with-050" src="https://github.com/user-attachments/assets/e99e298f-4c6c-4135-a87c-952aaa01ae65">
<img width="1021" alt="glossary-version-051" src="https://github.com/user-attachments/assets/b010198c-7a2f-4302-8372-e79c2edf63ba">
<img width="638" alt="glossary-centered-with-051" src="https://github.com/user-attachments/assets/23514342-bda9-4d65-8bb8-414230db5c96">
<img width="710" alt="minimal-fix-for-glossary-051" src="https://github.com/user-attachments/assets/7c1b2794-4dcf-4230-9387-67e1814c13fb">

**Comment by quachpas** [comment]
Hello @internettechnik, the only reason why you would need the additional show rule is if you have another conflicting show rule. By default, it's left-aligned (for LTR languages)
